import {
  ArrowLeft,
  ArrowRight,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Cog,
  Globe,
  LucideIcon,
  Menu,
  Quote,
  Share2,
  Timer,
  User,
  X,
} from "lucide-react";

export type Icon = LucideIcon;
export const Icons = {
  globe: Globe,
  menu: Menu,
  quote: Quote,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  cog: Cog,
  x: X,
  check: Check,
  chevronDown: ChevronDown,
  ChevronRight: ChevronRight,
  ChevronLeft: ChevronLeft,
  user: User,
  calendar: Calendar,
  timer: Timer,
  share: Share2,
};
